CREATE DATABASE SUMISAN;
GO
USE SUMISAN;
GO

-- USERS
CREATE TABLE USERS (
    UserId INT PRIMARY KEY IDENTITY(1,1),
    UserName VARCHAR(100) NOT NULL,
    Role VARCHAR(50) NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE(),
    LastLogin DATETIME NULL
);

-- MACHINES
CREATE TABLE MACHINES (
    Id SMALLINT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL
);

-- WASHINGS
CREATE TABLE WASHINGS (
    WashingId BIGINT PRIMARY KEY,
    MachineId SMALLINT NOT NULL FOREIGN KEY REFERENCES MACHINES(Id),
    StartUserId INT NOT NULL FOREIGN KEY REFERENCES USERS(UserId),
    EndUserId INT NULL FOREIGN KEY REFERENCES USERS(UserId),
    StartDate DATETIME NOT NULL,
    EndDate DATETIME NULL,
    Status CHAR(1) NOT NULL CHECK (Status IN ('P','F')),
    StartObservation VARCHAR(100) NULL,
    FinishObservation VARCHAR(100) NULL
);

-- PROTS
CREATE TABLE PROTS (
    Id INT PRIMARY KEY IDENTITY(1,1),
    WashingId BIGINT NOT NULL FOREIGN KEY REFERENCES WASHINGS(WashingId),
    ProtId VARCHAR(7) NOT NULL,
    BatchNumber VARCHAR(4) NOT NULL,
    BagNumber VARCHAR(5) NOT NULL
);

-- PHOTOS
CREATE TABLE PHOTOS (
    Id INT PRIMARY KEY IDENTITY(1,1),
    WashingId BIGINT NOT NULL FOREIGN KEY REFERENCES WASHINGS(WashingId),
    FileName VARCHAR(255) NOT NULL,
    FilePath VARCHAR(255) NOT NULL,
    CreatedAt DATETIME NOT NULL DEFAULT GETDATE()
);

-- PARAMETERS
CREATE TABLE PARAMETERS (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Name VARCHAR(50) NOT NULL,
    Value VARCHAR(255) NOT NULL
);
